//===-- LanguageNames.inc - Kernel Language runtime API names -------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
//===----------------------------------------------------------------------===//

#undef Error_t
#undef Malloc
#undef Free
#undef Memcpy
#undef DeviceSynchronize
#undef Success
#undef MemcpyKind
#undef MemcpyHostToHost
#undef MemcpyHostToDevice
#undef MemcpyDeviceToHost
#undef MemcpyDeviceToDevice
#undef MemcpyDefault
#undef HostAlloc
#undef MallocHost
#undef HostFree
